[tool.poetry]
name = "sqldir"
version = "0.3.0"
description = ""
authors = ["uname-n <git@defend.sh>"]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
